### ISSUE TITLE
Create table component

### ISSUE THREAD

**Issue by im36-123** [kufu/smarthr-ui#116]

**Comment by ouji-miyahara** [comment]
fixed design
![image](https://user-images.githubusercontent.com/1614892/63076364-ee316380-bf6f-11e9-9f20-2ae4aa7ff492.png)
https://smarthr.invisionapp.com/share/5WTGYPSJ4UR

**Comment by nabeliwo** [comment]
fix by https://github.com/kufu/smarthr-ui/pull/269
