### ISSUE TITLE
デザインと実装の差分解消依頼

### ISSUE THREAD

**Issue by ysasaki10** [kufu/smarthr-ui#183]
Loader
- メインカラーのものがプライマリーカラーと異なっているので、プライマリーへの変更をお願いします

Dropdown
- ulの上下paddingが10pxになっているので、8pxに変更お願いします
- liのpaddingを8px 16pxに変更をお願いします
- font-sizeを14pxに変更をお願いします
- colorを#333333に変更をお願いします

Pagenation
- radiusを4pxに変更をお願いします

**Comment by nabeliwo** [comment]
This issue will be moved to smarthr's internal jira ticket management.
