### ISSUE TITLE
company name is not aligned

### ISSUE THREAD

**Issue by is2ei** [kufu/smarthr-ui#2129]
It seems company name is not aligned correctly in `Footer` comnponent.
<img width="1439" alt="Screen Shot 2021-12-17 at 21 42 53" src="https://user-images.githubusercontent.com/3948353/146556893-73da52bf-8374-437c-967e-5d0038ee916d.png">
<img width="1440" alt="Screen Shot 2021-12-17 at 21 43 11" src="https://user-images.githubusercontent.com/3948353/146556903-d1fe4edf-9bf7-4b5c-a301-22175e54f162.png">

It could be solved easily by using `display: flex` and `margin: auto`, for example.
<img width="1440" alt="Screen Shot 2021-12-17 at 23 14 39" src="https://user-images.githubusercontent.com/3948353/146557527-15a43301-9e25-4266-b957-759d178a8ecf.png">

**Comment by uknmr** [comment]
Many thanks!
I'll fix it.
