### ISSUE TITLE
some markdown links are not formatted correctly

### ISSUE THREAD

**Issue by is2ei** [kufu/smarthr-ui#2130]
In `CONTRIBUTING.md`, some markdown links are not formatted correctly. 😅 

<img width="1370" alt="Screen Shot 2021-12-17 at 23 24 36" src="https://user-images.githubusercontent.com/3948353/146559061-8bf0d2db-189c-429c-8d4e-4aa8d9227382.png">

**Comment by uknmr** [comment]
Thank you!
I'll fix it in due course.
