### ISSUE TITLE
Modify Loader component

### ISSUE THREAD

**Issue by ysasaki10** [kufu/smarthr-ui#267]
Modify Background-color to Main(#00A5AB).

👻faluse
<img width="66" alt="スクリーンショット 2019-08-15 19 09 06" src="https://user-images.githubusercontent.com/12723757/63088977-66f4e780-bf91-11e9-8d1b-59842a25f808.png">

↓

✅true
<img width="58" alt="スクリーンショット 2019-08-15 19 11 37" src="https://user-images.githubusercontent.com/12723757/63088669-90614380-bf90-11e9-8be5-44d4762ec432.png">

**Comment by nabeliwo** [comment]
This issue will be moved to smarthr's internal jira ticket management.
