### ISSUE TITLE
Add theme change functionality. (テーマ変更機能を追加します。)

### ISSUE THREAD

**Issue by Aarav238** [kufu/smarthr-ui#3813]
I want to add dark mode / light mode functionality in it , so that it can become more user friendly and attractive.
(ダークモード/ライトモード機能を追加して、よりユーザーフレンドリーで魅力的なものにしたいと考えています。)

@kufu-guest

**Comment by uknmr** [comment]
ありがとうございます。
`createTheme()` を使ったテーマ変更機能がすでにあります。ダークテーマの標準提供は現状考えていません。
