### ISSUE TITLE
defaultPalette の色でコントラスト比が `4.5:1` に意図せず達していない組み合わせがある

### ISSUE THREAD

**Issue by masuP9** [kufu/smarthr-ui#778]
## 概要

前景色に `defaultPalette.TEXT_GREY: #767676` または `defaultPalette.TEXT_LINK: #007bc2` を利用し背景色に `defaultPalette.BACKGROUND: #f5f6fa` を利用した場合のコントラスト比が `4.5:1` を下回る。

背景色が `#fff` との組み合わせの場合のコントラスト比が `4.5:1` となるように設計されているが、背景色が `defaultPalette.BACKGROUND` になるケースも多く存在するため検討が必要。

具体例 👉 https://github.com/kufu/smarthr-ui/pull/768#discussion_r422839719

<img width="620" alt="色の組み合わせごとにコントラスト比を算出した表。グレーの #767676 と青の #007bc2 は#fffとの組み合わせだと4.5:1（AA）だが、#f5f6fa との組み合わせだと4.2:1 (AA)18
Pass, Large Text Only (3+)になっている" src="https://user-images.githubusercontent.com/6724665/81631625-39b36800-9443-11ea-8ffe-015bc7cbbd4a.png">

[ContrastGrid](http://contrast-grid.eightshapes.com/?background-colors=&foreground-colors=%23fff%0D%0A%23f5f6fa%0D%0A%23767676%0D%0A%23007bc2&es-color-form__tile-size=regular)

### `defaultPalette.TEXT_GREY`, `defaultPalette.TEXT_LINK` を `defaultPalette.BACKGROUND` との組み合わせでもコントラスト比を `4.5:1` 以上になるように変更する

- 大変（全体のイメージが変わるという意味で）
- WCAG 2.0 | JIS X 8341-3:2016 1.4.3 (AA)の達成基準を達成できる

### 微々たる差なので一旦許容する

- 対応コストを考えるとアリ。
- WCAG 2.0 | JIS X 8341-3:2016 1.4.3 (AA)の達成基準を達成できない

## 私見

正直微差なので現時点で数値に厳密になるよりかは、徐々に見やすくしていければと考えているので今すぐの対応は不要と考えています。

**Comment by versionfive** [comment]
@masuP9 こちらのPRで`TEXT_GREY`、`TEXT_LINK`に見直します。
テキストの配置が想定される`BACKGROUND`や`COLUMN`、`OVER_BACKGROUND`に対して`4.5:1`を確保しています。
https://github.com/kufu/smarthr-ui/pull/1407

**Comment by masuP9** [comment]
@versionfive `TEXT_GERY` と `TEXT_LINK` が `BACKGROUND` との組み合わせでも `4.5:1` 以上になりましたね 🎉 

<a href="https://contrast-grid.eightshapes.com/?background-colors=%23ffffff%2C%20White%0D%0A%23f8f7f6%2C%20BACKGROUND%20%2F%20COLUMN%0D%0A%23f2f1f0%2C%20OVER_BACKGROUND%0D%0A%23d6d3d0%2C%20ACTION_BACKGROUND&foreground-colors=%2323221f%2C%20TEXT_BLACK%0D%0A%23706d65%2C%20TEXT_GREY%0D%0A%230071c1%2C%20TEXT_LINK%0D%0A%230077c7%2C%20MAIN%0D%0A%23e01e5a%2C%20DANGER%0D%0A%23ff8800%2C%20WARNING&es-color-form__tile-size=large">
Contrast Grid
<img width="1155" alt="新しいカラーパレットの組み合わせのコントラストグリッド" src="https://user-images.githubusercontent.com/6724665/110742239-56921500-8279-11eb-8bcc-60487a31bc60.png">
</a>

この Issue で提議した組み合わせに関しては解決されているのでCloseします！

----

新しい `ACTION_BACKGROUND` と `TEXT_BLACK` 以外の組み合わせは気をつけたいですね。
