### ISSUE TITLE
Create datepicker component

### ISSUE THREAD

**Issue by nabeliwo** [kufu/smarthr-ui#88]

**Comment by ouji-miyahara** [comment]
fixed design
![image](https://user-images.githubusercontent.com/1614892/63076272-9b57ac00-bf6f-11e9-9d63-b0f9dc1dfaa8.png)
https://smarthr.invisionapp.com/share/UXTGYP3D4JE

**Comment by nabeliwo** [comment]
This issue will be moved to smarthr's internal jira ticket management.
